# Site settings
baseurl = "http://stereotypecreation.fr/"
theme = "stereotype-theme"

[params]
    name = "Sabrina Quindroit"
    email = "contact@stereotypecreation.fr"
    subtitle    = "Créations de graphisme textiles, illustrations et peintures"
    facebook    = "https://www.facebook.com/stereotypecreation/"
    pinterest   = "https://fr.pinterest.com/quindroit/"
    instagram   = "https://www.instagram.com/quindroitsabrina/"
    spotify     = "https://open.spotify.com/embed/user/spotify/playlist/6AV1SULGwX3OFyYzoZqokN?theme=white"



