# Site settings
baseurl = "http://stereotypecreation.fr/"
theme = "stereotype-theme"

[params]
    name = "Sabrina Quindroit"
    email = "quindroitsabrina@gmail.com"
    subtitle    = "Créations de graphisme textiles, illustrations et peintures"
    facebook    = "https://www.facebook.com/stereotypecreation/"
    pinterest   = "https://fr.pinterest.com/quindroit/"
    instagram   = "https://www.instagram.com/quindroitsabrina/"
    spotify     = "https://embed.spotify.com/?uri=spotify%3Auser%3Aquindroitsabrina%3Aplaylist%3A5SzhTCubCwoGXz1p0IWs1q?theme=white"



